# Generated by Django 5.0.10 on 2025-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="avatar_source",
            field=models.CharField(
                choices=[("G", "Hosted by Gravatar"), ("U", "Uploaded by user")],
                default="G",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="avatar_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="stream",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
