# Generated by Django 5.0.10 on 2025-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="bbb_url",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
