# Generated by Django 5.0.10 on 2025-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0644_stream_avatar_source_stream_avatar_version_and_more"),
        ("zerver", "0644_stream_bbb_url"),
    ]

    operations = []
