# Generated by Django 5.0.10 on 2025-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0645_merge_20250120_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorites",
            field=models.CharField(blank=True, default=""),
        ),
    ]
