# Generated by Django 5.0.10 on 2025-01-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0645_merge_20250120_1551"),
        ("zerver", "0646_userprofile_favorites"),
    ]

    operations = []
